name: CI
on: [create, push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: "poetry"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'
      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          make install
      - name: Run Lint
        run: make lint
      - name: Run Tests
        run: make test
      - name: Run Build
        run: make -C frontend build

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Deploy Package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish
